services:
  - type: web
    name: teleios-api
    runtime: node
    rootDir: backend
    buildCommand: npm run build
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@teleios.com
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        sync: false
